{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.systemlib",
    "module": "systemlib",
    "version": "1.0-20260227",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "systemlib-1.0-20260227.aar",
          "url": "systemlib-1.0-20260227.aar",
          "size": 108944,
          "sha512": "2c4f944162ce03207e11cc3cc8382e8471d4c5db0fc9b68227113b54f78fc6ecbf54f02343f5a6309721aae578862a2c1329a80a5d19a7f39cba365dc6503347",
          "sha256": "829abf197f86f7ab48e5d6bf7303a8357cfd31a5c990f48ae49996e67bab41e3",
          "sha1": "bf84a26f116fe172a5158625f1206b396e3a8b0a",
          "md5": "4bc5d969699fe103cf1d78d5384fda8b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.android.android12",
          "module": "android12",
          "version": {
            "requires": "1.0-20260227"
          }
        },
        {
          "group": "com.android.android13",
          "module": "android13",
          "version": {
            "requires": "1.0-20260227"
          }
        },
        {
          "group": "com.android.android14",
          "module": "android14",
          "version": {
            "requires": "1.0-20260227"
          }
        },
        {
          "group": "com.android.android15",
          "module": "android15",
          "version": {
            "requires": "1.0-20260227"
          }
        },
        {
          "group": "com.android.android16",
          "module": "android16",
          "version": {
            "requires": "1.0-20260227"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "systemlib-1.0-20260227.aar",
          "url": "systemlib-1.0-20260227.aar",
          "size": 108944,
          "sha512": "2c4f944162ce03207e11cc3cc8382e8471d4c5db0fc9b68227113b54f78fc6ecbf54f02343f5a6309721aae578862a2c1329a80a5d19a7f39cba365dc6503347",
          "sha256": "829abf197f86f7ab48e5d6bf7303a8357cfd31a5c990f48ae49996e67bab41e3",
          "sha1": "bf84a26f116fe172a5158625f1206b396e3a8b0a",
          "md5": "4bc5d969699fe103cf1d78d5384fda8b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "systemlib-1.0-20260227-sources.jar",
          "url": "systemlib-1.0-20260227-sources.jar",
          "size": 48963,
          "sha512": "d38255d810a0784ee819a4e017230b2cb70c74de4057ff7474b0316117a3cd738cb070905688b967144d91bcc3ec63caf679ea6da623762105ab96e1a52b62e8",
          "sha256": "31d3159543dc1355b247146316aea0840389ed12dcf8e653d4809e510d9330bd",
          "sha1": "5d4efc1fe1a5540b401a890142cfa2b04f868e3e",
          "md5": "f3191d40a401058f3cd70c664fdbfa62"
        }
      ]
    }
  ]
}
