{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.systemuix",
    "module": "systemuix",
    "version": "1.0-20230407",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "systemuix-1.0-20230407.aar",
          "url": "systemuix-1.0-20230407.aar",
          "size": 62146,
          "sha512": "02f645a0cc8c4d6d4e60efc70f849eb10926a911fcd523516ece24f31899bb64697191b538aaa654648f8f1d36e5b381fb0eb3d54c2cfe924bbe064f895d2a49",
          "sha256": "3450965770d4d7eed0f6c15f11c97bb58a325dc55c49bce26df9fde67c5bc0e4",
          "sha1": "a4db2b3f634246e8e59c51b1892af9e7fb3aa33b",
          "md5": "0b86f1a3d323d842cee71f2ae62e8f7d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.github.h4de5ing.base",
          "module": "base",
          "version": {
            "requires": "1.0-20221229"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "systemuix-1.0-20230407.aar",
          "url": "systemuix-1.0-20230407.aar",
          "size": 62146,
          "sha512": "02f645a0cc8c4d6d4e60efc70f849eb10926a911fcd523516ece24f31899bb64697191b538aaa654648f8f1d36e5b381fb0eb3d54c2cfe924bbe064f895d2a49",
          "sha256": "3450965770d4d7eed0f6c15f11c97bb58a325dc55c49bce26df9fde67c5bc0e4",
          "sha1": "a4db2b3f634246e8e59c51b1892af9e7fb3aa33b",
          "md5": "0b86f1a3d323d842cee71f2ae62e8f7d"
        }
      ]
    }
  ]
}
