{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.android12",
    "module": "android12",
    "version": "1.0-20260729",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android12-1.0-20260729.aar",
          "url": "android12-1.0-20260729.aar",
          "size": 784,
          "sha512": "aa86d893ad5184efcd44604d9be0f4767dc989c3caa71b22dbdf3d329630f9f612f8c64b78e4d14c67139c18d3ba01572b06bf5fe61373a9851cb660c5f4560e",
          "sha256": "52dde3456b57475f28e70ab32b0153bc3b1932bc14a2a11f0c7d476088013755",
          "sha1": "2168bae7fa8e71683324b79456b218722830ca93",
          "md5": "e4c2a2bc3c93e11af22a65bba21147ff"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android12-1.0-20260729.aar",
          "url": "android12-1.0-20260729.aar",
          "size": 784,
          "sha512": "aa86d893ad5184efcd44604d9be0f4767dc989c3caa71b22dbdf3d329630f9f612f8c64b78e4d14c67139c18d3ba01572b06bf5fe61373a9851cb660c5f4560e",
          "sha256": "52dde3456b57475f28e70ab32b0153bc3b1932bc14a2a11f0c7d476088013755",
          "sha1": "2168bae7fa8e71683324b79456b218722830ca93",
          "md5": "e4c2a2bc3c93e11af22a65bba21147ff"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android12-1.0-20260729-sources.jar",
          "url": "android12-1.0-20260729-sources.jar",
          "size": 4018,
          "sha512": "912e1d92f877dbe8bad306dce866310d455d55291d49a7fd19b60d65a8bba9c2831a30e7a85f39a3618831e183d1b6177533fc55263ff38537567f7394b48155",
          "sha256": "957dfda77b8b2025952b1e15f9136cb2292ab47346679890ca55e66a1dc475f7",
          "sha1": "c2d2ddc3e661e485c7c6cb277c832567cc2e4f0d",
          "md5": "c36c52d97d40506578891c47b4c5f57a"
        }
      ]
    }
  ]
}
