{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.android15",
    "module": "android15",
    "version": "1.0-20260601",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android15-1.0-20260601.aar",
          "url": "android15-1.0-20260601.aar",
          "size": 2620,
          "sha512": "2dd9ba889fbabd8272cd52cd9075b1d19b038b2bdcb81348f9961ec5fac12c619297331991be4493bc9aebcfd3e4d2d4e009d262593aa6b566c08dd82b76a0c1",
          "sha256": "04b4973ea7ca81e3b31e0210c21bd448e0acf119241d6aced4f93924e93fbbc9",
          "sha1": "d9b98588b73dbeb085d554fa3269dc400fdda597",
          "md5": "f785dec90da335b7c0959923ff0be40e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android15-1.0-20260601.aar",
          "url": "android15-1.0-20260601.aar",
          "size": 2620,
          "sha512": "2dd9ba889fbabd8272cd52cd9075b1d19b038b2bdcb81348f9961ec5fac12c619297331991be4493bc9aebcfd3e4d2d4e009d262593aa6b566c08dd82b76a0c1",
          "sha256": "04b4973ea7ca81e3b31e0210c21bd448e0acf119241d6aced4f93924e93fbbc9",
          "sha1": "d9b98588b73dbeb085d554fa3269dc400fdda597",
          "md5": "f785dec90da335b7c0959923ff0be40e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android15-1.0-20260601-sources.jar",
          "url": "android15-1.0-20260601-sources.jar",
          "size": 1427,
          "sha512": "24febecfd3205e6dcde7908a70bec584ab7ed1e5c0042374db3b4f805ee888532e717222387fa5f48658a2252a175c355dd17c3f6a0eac4ac4920c516b107eb3",
          "sha256": "43f94be32bea3d750506628fe404f9219971b840cbb37a64bf1855b4a4fc4f7f",
          "sha1": "6c3f3e22db90cd006ed61fdbc812ed1020745a6f",
          "md5": "bb3de879ea8bf40986dd200b2f7a5b4e"
        }
      ]
    }
  ]
}
