{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.systemuix",
    "module": "systemuix",
    "version": "1.0-20230324",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "systemuix-1.0-20230324.aar",
          "url": "systemuix-1.0-20230324.aar",
          "size": 63367,
          "sha512": "e67fc4363bdab1bf84966a7480f146768bc9d2bddd84373857b3564c7b98354661e8387ad0226878fabf67992f75ad7dc3301e700e82b0bd975f6f009734dd1d",
          "sha256": "8acb376a8251e526e5136ce45fb78df1d0e6240192a78fb23b54e0b11bf201df",
          "sha1": "6c5ec39f33c03738dbb905bee346327f781ce1fb",
          "md5": "4f5969f22dfe596a54f26e0442377571"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.github.h4de5ing.base",
          "module": "base",
          "version": {
            "requires": "1.0-20221229"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "systemuix-1.0-20230324.aar",
          "url": "systemuix-1.0-20230324.aar",
          "size": 63367,
          "sha512": "e67fc4363bdab1bf84966a7480f146768bc9d2bddd84373857b3564c7b98354661e8387ad0226878fabf67992f75ad7dc3301e700e82b0bd975f6f009734dd1d",
          "sha256": "8acb376a8251e526e5136ce45fb78df1d0e6240192a78fb23b54e0b11bf201df",
          "sha1": "6c5ec39f33c03738dbb905bee346327f781ce1fb",
          "md5": "4f5969f22dfe596a54f26e0442377571"
        }
      ]
    }
  ]
}
