{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.android15",
    "module": "android15",
    "version": "1.0-20260729",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android15-1.0-20260729.aar",
          "url": "android15-1.0-20260729.aar",
          "size": 2617,
          "sha512": "d973cf0b41cc0806ccda3d5b76a245306d93e308fadeaf9a7c2b7c5d0e2645929892145bf6197780106eb4330471f11409c67aaa4fa07aaf45594db4327667c7",
          "sha256": "34d0455e3e574c149ae756a88d7fdd62c0859f5e77b8d234f70feb4fa73e5a6b",
          "sha1": "196049431572628e65d4191dc54b9906a7801a6e",
          "md5": "ede87f527c2a058aaddb8b3f186cef0c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android15-1.0-20260729.aar",
          "url": "android15-1.0-20260729.aar",
          "size": 2617,
          "sha512": "d973cf0b41cc0806ccda3d5b76a245306d93e308fadeaf9a7c2b7c5d0e2645929892145bf6197780106eb4330471f11409c67aaa4fa07aaf45594db4327667c7",
          "sha256": "34d0455e3e574c149ae756a88d7fdd62c0859f5e77b8d234f70feb4fa73e5a6b",
          "sha1": "196049431572628e65d4191dc54b9906a7801a6e",
          "md5": "ede87f527c2a058aaddb8b3f186cef0c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android15-1.0-20260729-sources.jar",
          "url": "android15-1.0-20260729-sources.jar",
          "size": 1427,
          "sha512": "24febecfd3205e6dcde7908a70bec584ab7ed1e5c0042374db3b4f805ee888532e717222387fa5f48658a2252a175c355dd17c3f6a0eac4ac4920c516b107eb3",
          "sha256": "43f94be32bea3d750506628fe404f9219971b840cbb37a64bf1855b4a4fc4f7f",
          "sha1": "6c3f3e22db90cd006ed61fdbc812ed1020745a6f",
          "md5": "bb3de879ea8bf40986dd200b2f7a5b4e"
        }
      ]
    }
  ]
}
