{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.android13",
    "module": "android13",
    "version": "1.0-20260729",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android13-1.0-20260729.aar",
          "url": "android13-1.0-20260729.aar",
          "size": 7815,
          "sha512": "022b7babaf07c2688e32b42e10fdb635f659a8b51925ab466fb54ccae71191933ea90821f2c35f182d13a19f5592d2f463d8359e91ceba57df739e1da0a57e00",
          "sha256": "2a8a6aed3a75aefc8267003607eb0d140f3b6d957fe8571e1b9290254f6dc97d",
          "sha1": "4f2b8f41d8fb00011d457f8959e5c7f741ffe085",
          "md5": "c6af7778e2d35513918cfcd732b812e9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android13-1.0-20260729.aar",
          "url": "android13-1.0-20260729.aar",
          "size": 7815,
          "sha512": "022b7babaf07c2688e32b42e10fdb635f659a8b51925ab466fb54ccae71191933ea90821f2c35f182d13a19f5592d2f463d8359e91ceba57df739e1da0a57e00",
          "sha256": "2a8a6aed3a75aefc8267003607eb0d140f3b6d957fe8571e1b9290254f6dc97d",
          "sha1": "4f2b8f41d8fb00011d457f8959e5c7f741ffe085",
          "md5": "c6af7778e2d35513918cfcd732b812e9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android13-1.0-20260729-sources.jar",
          "url": "android13-1.0-20260729-sources.jar",
          "size": 2138,
          "sha512": "679f46a0bbd6fd92b57113d3fb5531c797e4f68bd32e9b9dfcb47547437aef35fc7f5ea2ce7c0ff82febbad05e1fc279f3d4c341ff947a694036ff898eeea35b",
          "sha256": "ccfbaeac8c8217c8d873ab2229340e81e0749a8005019bc00dce4acbb495d20f",
          "sha1": "991efe7c2d5482c66a36b99de1dd26fc34824b92",
          "md5": "b7eb17fde829258de24d1604de29de2a"
        }
      ]
    }
  ]
}
