{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.hideapi",
    "module": "hideapi",
    "version": "1.0-20250619",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "hideapi-1.0-20250619.aar",
          "url": "hideapi-1.0-20250619.aar",
          "size": 4928,
          "sha512": "de73239f772860fb003d4042165cd61b2b30045dc8b7a6a0b66d4956147965cae4bc83f49fe7852d7d3ca3c4ee891a3b77149b3d471d6d91bbdcd76d19ae374a",
          "sha256": "1c3335167741b8b470f07ddd3f9f291a42c1f33f42ed34d3c9ca6e1ce7f167c1",
          "sha1": "1049cec87ea07cf91b25b1226f497ff40f36a7f2",
          "md5": "a53bc4bd36467fce6e9dcb8115484e21"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "hideapi-1.0-20250619.aar",
          "url": "hideapi-1.0-20250619.aar",
          "size": 4928,
          "sha512": "de73239f772860fb003d4042165cd61b2b30045dc8b7a6a0b66d4956147965cae4bc83f49fe7852d7d3ca3c4ee891a3b77149b3d471d6d91bbdcd76d19ae374a",
          "sha256": "1c3335167741b8b470f07ddd3f9f291a42c1f33f42ed34d3c9ca6e1ce7f167c1",
          "sha1": "1049cec87ea07cf91b25b1226f497ff40f36a7f2",
          "md5": "a53bc4bd36467fce6e9dcb8115484e21"
        }
      ]
    }
  ]
}
