{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.systemuix",
    "module": "systemuix",
    "version": "1.0-20230529",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "systemuix-1.0-20230529.aar",
          "url": "systemuix-1.0-20230529.aar",
          "size": 40451,
          "sha512": "0caa9774152f0a5cbcc2f53c60d24984e60c521d2293ea652c713d82a98085f7c37b4f1347f84677ada77681e791f719d267516b612020eb137be7a66ad12e8c",
          "sha256": "4475e3ac4b0b29a0e2abeb0061f3391ddaa58a56c0c9e6afe7e40d0a0685b437",
          "sha1": "f04e293211260aedaa600c26997aa52e883b80ef",
          "md5": "df40c32d9d042fc93ccc809793f86134"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.github.h4de5ing.base",
          "module": "base",
          "version": {
            "requires": "1.0-20221229"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "systemuix-1.0-20230529.aar",
          "url": "systemuix-1.0-20230529.aar",
          "size": 40451,
          "sha512": "0caa9774152f0a5cbcc2f53c60d24984e60c521d2293ea652c713d82a98085f7c37b4f1347f84677ada77681e791f719d267516b612020eb137be7a66ad12e8c",
          "sha256": "4475e3ac4b0b29a0e2abeb0061f3391ddaa58a56c0c9e6afe7e40d0a0685b437",
          "sha1": "f04e293211260aedaa600c26997aa52e883b80ef",
          "md5": "df40c32d9d042fc93ccc809793f86134"
        }
      ]
    }
  ]
}
