package com.android.mdmsdk

enum class ConfigEnum {
    DISABLE_HOME,
    DISABLE_RECENT,
    DISABLE_BACK,
    DISABLE_NAVIGATION,
    DISABLE_STATUS,

    DISABLE_USB_DATA,

    DISABLE_BLUETOOTH,
    DISABLE_WIFI,
    DISABLE_DATA_CONNECTIVITY,
    DISABLE_GPS,
    DISABLE_MICROPHONE,
    DISABLE_SCREEN_SHOT,
    DISABLE_SCREEN_CAPTURE,
    DISABLE_TF_CARD,
    DISABLE_PHONE_CALL,
    DISABLE_HOT_SPOT,
    DISABLE_SMS,
    DISABLE_MMS,
    DISABLE_SYSTEM_UPDATE,
    DISABLE_RESTORE_FACTORY,
}