package com.android.mdmsdk

enum class ConfigEnum {
    DISABLE_HOME_VALUE,
    DISABLE_RECENT_VALUE,
    DISABLE_BACK_VALUE,
    DISABLE_NAVIGATION_VALUE,//TODO
    DISABLE_STATUS_VALUE,

    DISABLE_USB_DATA,//==adb //TODO

    DISABLE_BLUETOOTH_VALUE,
    DISABLE_WIFI_VALUE,
    DISABLE_DATA_VALUE,
    DISABLE_GPS_VALUE,
    DISABLE_CAMERA_VALUE,
    DISABLE_MICROPHONE_VALUE,
    DISABLE_SCREEN_SHOT_VALUE,
    DISABLE_STORAGE_VALUE,
    DISABLE_PHONE_CALL_VALUE,
    DISABLE_HOT_SPOT_VALUE,
    DISABLE_SMS_VALUE,
    DISABLE_SYSTEM_UPDATE_VALUE,
    DISABLE_RESTORE_FACTORY_VALUE,
    DISABLE_INSTALL_APP_VALUE,
    INSTALL_APP,
    DISABLE_UNINSTALL_APP_VALUE,
}