package com.android.mdmsdk

enum class PackageManagerEnum {
    DISABLE_INSTALL_ADD,
    DISABLE_INSTALL_REMOVE,
    INSTALL_ADD,
    INSTALL_REMOVE,
    DISABLE_UNINSTALL_ADD,
    DISABLE_UNINSTALL_REMOVE,
    PERSISTENT_ADD,
    PERSISTENT_REMOVE,
    SUPER_WHITE_ADD,
    SUPER_WHITE_REMOVE,
}