{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.android14",
    "module": "android14",
    "version": "1.0-20250327",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "android14-1.0-20250327.aar",
          "url": "android14-1.0-20250327.aar",
          "size": 2055,
          "sha512": "b8995551c60456602e46718886c916919e039f89cd6a749ff2b1bd9fd932d3a40a769cdf049c164865018e5e38e3256973bcfeddcb1cc722b997f8d07f1a1e31",
          "sha256": "35e427f91c8053191b161ede3181041363eab203387474d447fccc74c43de44a",
          "sha1": "1cc8febfffbb6d0f01ad9778335b7a2d0a5d4a80",
          "md5": "16424e0b0421fdc537beb44ee106f1c5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "android14-1.0-20250327.aar",
          "url": "android14-1.0-20250327.aar",
          "size": 2055,
          "sha512": "b8995551c60456602e46718886c916919e039f89cd6a749ff2b1bd9fd932d3a40a769cdf049c164865018e5e38e3256973bcfeddcb1cc722b997f8d07f1a1e31",
          "sha256": "35e427f91c8053191b161ede3181041363eab203387474d447fccc74c43de44a",
          "sha1": "1cc8febfffbb6d0f01ad9778335b7a2d0a5d4a80",
          "md5": "16424e0b0421fdc537beb44ee106f1c5"
        }
      ]
    }
  ]
}
