{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.android12",
    "module": "android12",
    "version": "1.0-20220411",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "android12-1.0-20220411.aar",
          "url": "android12-1.0-20220411.aar",
          "size": 3325,
          "sha512": "65ab34e93cdc81d144a0422d5f9c8c8227b24de7d8f9f78b4f99fdc741b7229856a30e36595f08e513a569673b0711b2bc7e5599134a035d268371919efe5f27",
          "sha256": "d0787d4e5b0926acaf9b1d0f915183fb40e41371ed4191c4717edf9d39e08f78",
          "sha1": "7f75ddf918a71b3c301ea716bf71bda3692cc176",
          "md5": "f661759493ed0747a5f659206c0e219d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "android12-1.0-20220411.aar",
          "url": "android12-1.0-20220411.aar",
          "size": 3325,
          "sha512": "65ab34e93cdc81d144a0422d5f9c8c8227b24de7d8f9f78b4f99fdc741b7229856a30e36595f08e513a569673b0711b2bc7e5599134a035d268371919efe5f27",
          "sha256": "d0787d4e5b0926acaf9b1d0f915183fb40e41371ed4191c4717edf9d39e08f78",
          "sha1": "7f75ddf918a71b3c301ea716bf71bda3692cc176",
          "md5": "f661759493ed0747a5f659206c0e219d"
        }
      ]
    }
  ]
}
