{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.mdmsdk",
    "module": "mdmsdk",
    "version": "1.0-20220425",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "mdmsdk-1.0-20220425.aar",
          "url": "mdmsdk-1.0-20220425.aar",
          "size": 22269,
          "sha512": "9e7251a4ef6712f11398444d4c0294232cfacfab52f6f34732124e5e90fc25a8b44695e84555a68e2b18d6d87e0b70fa1619efe7e6f0a35f46fc31f789c6b9fb",
          "sha256": "679a06da86c2cecbf79fc4e93a44fdd45060d6d2f4ab350a5e5386e10117375c",
          "sha1": "413c994fc815f14ffddb6909ed806ecef7efc3d9",
          "md5": "0c434a9a169cb5d6dedbbd528444c8b7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "mdmsdk-1.0-20220425.aar",
          "url": "mdmsdk-1.0-20220425.aar",
          "size": 22269,
          "sha512": "9e7251a4ef6712f11398444d4c0294232cfacfab52f6f34732124e5e90fc25a8b44695e84555a68e2b18d6d87e0b70fa1619efe7e6f0a35f46fc31f789c6b9fb",
          "sha256": "679a06da86c2cecbf79fc4e93a44fdd45060d6d2f4ab350a5e5386e10117375c",
          "sha1": "413c994fc815f14ffddb6909ed806ecef7efc3d9",
          "md5": "0c434a9a169cb5d6dedbbd528444c8b7"
        }
      ]
    }
  ]
}
