{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.android12",
    "module": "android12",
    "version": "1.0-20260709",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android12-1.0-20260709.aar",
          "url": "android12-1.0-20260709.aar",
          "size": 787,
          "sha512": "b72feebd037e7d5c3a3e4a8bc962dc3cde3ab1b16b0e4b38ac4ff534efecb6c097e440b75a040fdb0828251bf4561002d1d7ebf538abc0ad78bdf594c1fb7eab",
          "sha256": "38461b176dc276a782123227323004a628812c3573ff0240a5e6228509ddaf12",
          "sha1": "6094599b681b7650668ee89201278271acac5b41",
          "md5": "285e19076cab2cfd792493d1a04fc11a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android12-1.0-20260709.aar",
          "url": "android12-1.0-20260709.aar",
          "size": 787,
          "sha512": "b72feebd037e7d5c3a3e4a8bc962dc3cde3ab1b16b0e4b38ac4ff534efecb6c097e440b75a040fdb0828251bf4561002d1d7ebf538abc0ad78bdf594c1fb7eab",
          "sha256": "38461b176dc276a782123227323004a628812c3573ff0240a5e6228509ddaf12",
          "sha1": "6094599b681b7650668ee89201278271acac5b41",
          "md5": "285e19076cab2cfd792493d1a04fc11a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android12-1.0-20260709-sources.jar",
          "url": "android12-1.0-20260709-sources.jar",
          "size": 4018,
          "sha512": "912e1d92f877dbe8bad306dce866310d455d55291d49a7fd19b60d65a8bba9c2831a30e7a85f39a3618831e183d1b6177533fc55263ff38537567f7394b48155",
          "sha256": "957dfda77b8b2025952b1e15f9136cb2292ab47346679890ca55e66a1dc475f7",
          "sha1": "c2d2ddc3e661e485c7c6cb277c832567cc2e4f0d",
          "md5": "c36c52d97d40506578891c47b4c5f57a"
        }
      ]
    }
  ]
}
