{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.android16",
    "module": "android16",
    "version": "1.0-20260601",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android16-1.0-20260601.aar",
          "url": "android16-1.0-20260601.aar",
          "size": 2178,
          "sha512": "f1b233ad148b2e3a42c924aaf7765773179738e03878f7e9dd18c278f0089a13e43b62e5f9d4c87b748c41cb7009b66ad65345bcb3ee26260e19a8add201f10d",
          "sha256": "dd4c448cc2f34c93f6254da52feb510cdb3ee3e9d2331340615602138de3bdaf",
          "sha1": "3d68bbeacf7cb46c7e4e6429597c5f7687e8d8e5",
          "md5": "b1dbc1fe154211f19dbc3d589b7cf329"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android16-1.0-20260601.aar",
          "url": "android16-1.0-20260601.aar",
          "size": 2178,
          "sha512": "f1b233ad148b2e3a42c924aaf7765773179738e03878f7e9dd18c278f0089a13e43b62e5f9d4c87b748c41cb7009b66ad65345bcb3ee26260e19a8add201f10d",
          "sha256": "dd4c448cc2f34c93f6254da52feb510cdb3ee3e9d2331340615602138de3bdaf",
          "sha1": "3d68bbeacf7cb46c7e4e6429597c5f7687e8d8e5",
          "md5": "b1dbc1fe154211f19dbc3d589b7cf329"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android16-1.0-20260601-sources.jar",
          "url": "android16-1.0-20260601-sources.jar",
          "size": 1184,
          "sha512": "aeb160bd1a9f4a2cc1ad11e29635f6173d9fc8a7ca7e7003f47bb61db254ccd3fd5ccd7789bc08d0173e893a6c05424f36592966640ebed6a966a244a5ccfaf1",
          "sha256": "9435a191c6cf330123edd6b51687a0ac44b25951c20725689ac7505d2bf5c141",
          "sha1": "fc3037b9b8917e740e50194f23fa5d7b6d116e0d",
          "md5": "b120a4568350d0e3457138cff1f5a751"
        }
      ]
    }
  ]
}
