{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.android12",
    "module": "android12",
    "version": "1.0-20250327",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "android12-1.0-20250327.aar",
          "url": "android12-1.0-20250327.aar",
          "size": 6200,
          "sha512": "2d9551672a0b85dc0a2087f7e762684658c169a02281e074cd5175edb8e57ed3019360e4d14c419a80814e9736817bb763886fa6b04afcd4df3f591962445f52",
          "sha256": "37b42c372c2652c53a736abeeaf28cd1e19e4b7de8074e321b192f82e6f85843",
          "sha1": "245aff0bb01b5eb1d40dbce03bad35d241461fc7",
          "md5": "521137cc49779578278f1d6bcbd762a4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "android12-1.0-20250327.aar",
          "url": "android12-1.0-20250327.aar",
          "size": 6200,
          "sha512": "2d9551672a0b85dc0a2087f7e762684658c169a02281e074cd5175edb8e57ed3019360e4d14c419a80814e9736817bb763886fa6b04afcd4df3f591962445f52",
          "sha256": "37b42c372c2652c53a736abeeaf28cd1e19e4b7de8074e321b192f82e6f85843",
          "sha1": "245aff0bb01b5eb1d40dbce03bad35d241461fc7",
          "md5": "521137cc49779578278f1d6bcbd762a4"
        }
      ]
    }
  ]
}
