{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.systemlib",
    "module": "systemlib",
    "version": "1.0-20220907",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "systemlib-1.0-20220907.aar",
          "url": "systemlib-1.0-20220907.aar",
          "size": 42556,
          "sha512": "bbe35c24fef063452340704af03452b26ac997362daa7e0c9da188372052af342db16ecaa391ba42fc54087ebf9792c61d7f01900bebf7ebdfdc50dae338551a",
          "sha256": "c03f6a64688857fd3310fa93258e9d42f3c0489ecf1eb44159b2623835280a9f",
          "sha1": "2aeeb6093c0ebb1c742bf6a0155d812fd1e429e6",
          "md5": "fe39d4b3a070e6959361fc39ba697ead"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "SystemFunction",
          "module": "Android12",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "systemlib-1.0-20220907.aar",
          "url": "systemlib-1.0-20220907.aar",
          "size": 42556,
          "sha512": "bbe35c24fef063452340704af03452b26ac997362daa7e0c9da188372052af342db16ecaa391ba42fc54087ebf9792c61d7f01900bebf7ebdfdc50dae338551a",
          "sha256": "c03f6a64688857fd3310fa93258e9d42f3c0489ecf1eb44159b2623835280a9f",
          "sha1": "2aeeb6093c0ebb1c742bf6a0155d812fd1e429e6",
          "md5": "fe39d4b3a070e6959361fc39ba697ead"
        }
      ]
    }
  ]
}
