{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.systemuix",
    "module": "systemuix",
    "version": "1.0-20230322",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "systemuix-1.0-20230322.aar",
          "url": "systemuix-1.0-20230322.aar",
          "size": 61697,
          "sha512": "c4cbd6e07737c6c68ee08bbb5bbc71ca005c43a7d09d885132bbc95a644bc8cb2af455f863aecad39ad1e69408adb69c30b0ebb14c97f3386091031cc4ecee7b",
          "sha256": "2a283a8e579483bfca9f676313a826b8def1cccff0de73d7d22e1ffbff217949",
          "sha1": "a8a413ffcc72af0cad803c81be4f1ad86a78a412",
          "md5": "2c3cd8644873458778f12ea16471d22b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.github.h4de5ing.base",
          "module": "base",
          "version": {
            "requires": "1.0-20221229"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "systemuix-1.0-20230322.aar",
          "url": "systemuix-1.0-20230322.aar",
          "size": 61697,
          "sha512": "c4cbd6e07737c6c68ee08bbb5bbc71ca005c43a7d09d885132bbc95a644bc8cb2af455f863aecad39ad1e69408adb69c30b0ebb14c97f3386091031cc4ecee7b",
          "sha256": "2a283a8e579483bfca9f676313a826b8def1cccff0de73d7d22e1ffbff217949",
          "sha1": "a8a413ffcc72af0cad803c81be4f1ad86a78a412",
          "md5": "2c3cd8644873458778f12ea16471d22b"
        }
      ]
    }
  ]
}
