{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.systemuix",
    "module": "systemuix",
    "version": "1.0-20230322",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "systemuix-1.0-20230322.aar",
          "url": "systemuix-1.0-20230322.aar",
          "size": 60738,
          "sha512": "4a768c4e6e9ac5fa0c13e82670232ccb47b532b4a98d3710fa756420d61ff24cc95e3e1d13009752e6530d167f6e7c5941aff2ff0025ea1e8bb37b9df20cc57a",
          "sha256": "24f52581e6162ccaeab7fc5c4639f81364002995dd248e97396fffc28cc131ce",
          "sha1": "3fc3a1b8ccf4f3447c2a58bd0edd3736763b3c18",
          "md5": "2326126f812ffc8a7e22e8bac1cbad33"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.github.h4de5ing.base",
          "module": "base",
          "version": {
            "requires": "1.0-20221229"
          }
        },
        {
          "group": "SystemFunction",
          "module": "SystemLib",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "SystemFunction",
          "module": "Android12",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "systemuix-1.0-20230322.aar",
          "url": "systemuix-1.0-20230322.aar",
          "size": 60738,
          "sha512": "4a768c4e6e9ac5fa0c13e82670232ccb47b532b4a98d3710fa756420d61ff24cc95e3e1d13009752e6530d167f6e7c5941aff2ff0025ea1e8bb37b9df20cc57a",
          "sha256": "24f52581e6162ccaeab7fc5c4639f81364002995dd248e97396fffc28cc131ce",
          "sha1": "3fc3a1b8ccf4f3447c2a58bd0edd3736763b3c18",
          "md5": "2326126f812ffc8a7e22e8bac1cbad33"
        }
      ]
    }
  ]
}
