{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.mdmsdk",
    "module": "mdmsdk",
    "version": "1.0-20220907",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "mdmsdk-1.0-20220907.aar",
          "url": "mdmsdk-1.0-20220907.aar",
          "size": 30320,
          "sha512": "a05a29fe74a4c0c92bd92ee3046ed59d21322067e29a34963ff06ed1343113b0b48848db709eeb1ae45970ad86f4bccc69327cf4f72292e6fa2fbfd82238b614",
          "sha256": "c29ecbefa5feab27d4400352b6609d5e823dcb0060f32881672aac3e808ef987",
          "sha1": "7c26634303cc7a70486050e92321deedb0f0c5a7",
          "md5": "03d3b1db1d72cd01588e6ad6a62172c6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "mdmsdk-1.0-20220907.aar",
          "url": "mdmsdk-1.0-20220907.aar",
          "size": 30320,
          "sha512": "a05a29fe74a4c0c92bd92ee3046ed59d21322067e29a34963ff06ed1343113b0b48848db709eeb1ae45970ad86f4bccc69327cf4f72292e6fa2fbfd82238b614",
          "sha256": "c29ecbefa5feab27d4400352b6609d5e823dcb0060f32881672aac3e808ef987",
          "sha1": "7c26634303cc7a70486050e92321deedb0f0c5a7",
          "md5": "03d3b1db1d72cd01588e6ad6a62172c6"
        }
      ]
    }
  ]
}
