{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.android12",
    "module": "android12",
    "version": "1.0-20260813",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android12-1.0-20260813.aar",
          "url": "android12-1.0-20260813.aar",
          "size": 9400,
          "sha512": "b26f7e9d2f0b08745906fe6d35ff0c0744b00f5046eccebc8f5c747ba0d8096c9ff74a2d58ff227f0e011d44ff5f19c6f3da1e4b5c04048c210bceabe815bff3",
          "sha256": "17763f898b5cbca3070c7157020c7b3781c640292d682e01bce6b08a76193c59",
          "sha1": "2302638b98a776f2f068dae8a0da56394968461a",
          "md5": "f14a8b851928456614c0a2974d5142d2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android12-1.0-20260813.aar",
          "url": "android12-1.0-20260813.aar",
          "size": 9400,
          "sha512": "b26f7e9d2f0b08745906fe6d35ff0c0744b00f5046eccebc8f5c747ba0d8096c9ff74a2d58ff227f0e011d44ff5f19c6f3da1e4b5c04048c210bceabe815bff3",
          "sha256": "17763f898b5cbca3070c7157020c7b3781c640292d682e01bce6b08a76193c59",
          "sha1": "2302638b98a776f2f068dae8a0da56394968461a",
          "md5": "f14a8b851928456614c0a2974d5142d2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android12-1.0-20260813-sources.jar",
          "url": "android12-1.0-20260813-sources.jar",
          "size": 4018,
          "sha512": "912e1d92f877dbe8bad306dce866310d455d55291d49a7fd19b60d65a8bba9c2831a30e7a85f39a3618831e183d1b6177533fc55263ff38537567f7394b48155",
          "sha256": "957dfda77b8b2025952b1e15f9136cb2292ab47346679890ca55e66a1dc475f7",
          "sha1": "c2d2ddc3e661e485c7c6cb277c832567cc2e4f0d",
          "md5": "c36c52d97d40506578891c47b4c5f57a"
        }
      ]
    }
  ]
}
